### PR TITLE
added map and filter

### PR DESCRIPTION
**Pull request by vokeio**
### Requirements
None.

### Description of the Change
Added "map" and "filter" to the language syntax.

### Alternate Designs
None.

### Benefits
Better syntax highlighting. 

### Possible Drawbacks
None.

### Applicable Issues
None.

### CODE REVIEW

**Comment by AlexanderElias** [comment]
This is my first Atom pull request. Let me know if I need to do anything else to fulfill requirements.

**Comment by AlexanderElias** [comment]
Not sure what went wrong with the CI build. It seems like something went wrong with the RVM package.

**Comment by atomiks** [comment]
I opened #643 which covers some more methods.

Surprised this went totally ignored though? 😕

**Comment by 50Wliu** [comment]
Thanks very much for reaching out!

As you may have heard, we are migrating from our old [first-mate grammar engine](https://github.com/atom/first-mate) to the [new Tree-sitter engine](https://blog.github.com/2018-10-31-atoms-new-parsing-system/). This will enable a number of new features, more consistent syntax highlighting, and better performance, among other benefits. In order to free up our limited resources, we have decided to stop maintaining the first-mate grammar when there is a built-in Tree-sitter grammar available. Since this PR applies only to the first-mate grammar, we are going to close it.

Thanks again for your interest in Atom.

**Pull request closed without merging**
