### PR TITLE
improve function snippet

### PR DESCRIPTION
**Pull request by Hurtak**
- `function_name` renamed to `functionName` because calemCase is more common in JavaScript world
- removed `argument` while keeping tab stop 
  - improves writing of functions with no parameters
  - does not change writing of functions with 1+ parameters
- removed comment `// body ...` because it's useless and sometimes it slows us down when we are not using tab stops, if we are using tab stops experience is the same

comparison of 2 snippets

### CODE REVIEW

**Comment by 50Wliu** [comment]
Can you fix the other snippets as well that are using underscore_case as well as `//body`?

**Comment by Hurtak** [comment]
fixed

**Comment by 50Wliu** [comment]
Looks like there's some conflicts - can you please rebase?  Thanks!

**Comment by Hurtak** [comment]
rebased

**Comment by 50Wliu** [comment]
:+1:

**Pull request merged**
