### PR TITLE
Correctly mark $ prefixed vars as instance constructors

### PR DESCRIPTION
**Pull request by adambuczynski**
E.g. `new $thing()` 
It will now mark $thing as an instance constructor.

### CODE REVIEW

**Comment by 50Wliu** [comment]
Can you please add specs to this?  Thanks.

**Comment by adambuczynski** [comment]
Yep will do, cheers.

**Comment by adambuczynski** [comment]
Why are the javascript language specs written in coffeescript.... :(

**Comment by adambuczynski** [comment]
@50Wliu good to go!

**Comment by 50Wliu** [comment]
Thanks!

**Pull request merged**
