### PR TITLE
Don't capture whitespace as `storage.type.arrow.js`

### PR DESCRIPTION
**Pull request by 50Wliu**
Self-explanatory.  Only the arrow itself should be captured.

### CODE REVIEW

**Comment by 50Wliu** [comment]
Note: if this is merged before #248 then the spec for that will have to be updated, and vice versa.

**Comment by kevinsawicki** [comment]
I've merged #248, does this PR need to be updated?

**Comment by 50Wliu** [comment]
Yep, updated!

**Comment by kevinsawicki** [comment]
:+1: :ship:

**Pull request merged**
