### PR TITLE
Added "async" keyword

### PR DESCRIPTION
**Pull request by nkt**

### CODE REVIEW

**Comment by 50Wliu** [comment]
`async` should already be tokenized correctly - can you please share an example where it isn't?  Thanks.

**Comment by nkt** [comment]
Actually it doesn't highlight as a keyword like await.
2015-08-06 03-47-10 untitled - users nkt projects pochin api - atom

**Comment by mehcode** [comment]
@50Wliu It is also not highlighted inside of a class

```js
class Foo {
  async bar() {
  }
}
```

**Comment by 50Wliu** [comment]
Ok, thanks.  Looks like it's only supported in a couple of places.

**Comment by 50Wliu** [comment]
So everywhere where async is supported (such as `async function hi()`), it's tokenized as a `storage.modifier.js`.  Do you have any opinions on whether it should stay as `storage.modifier` or change everything to `keyword.operator`?

**Comment by Victorystick** [comment]
What is the convention (TextMate/Atom)? One could be strict about all keywords being marked with the `keyword` scope, but on the other hand that might make for annoying highlighting, and `storage.modifier` may improve readability.

**Comment by kevinsawicki** [comment]
> Do you have any opinions on whether it should stay as storage.modifier or change everything to keyword.operator?

I think using `storage.modifier` for this case to start is the right move so that all instances are consistent.

I'm going to merge this PR as is and just tweak it on master, thanks for this change :+1:

**Comment by nkt** [comment]
@kevinsawicki great! Can you publish new release?

**Comment by kevinsawicki** [comment]
> Can you publish new release?

I published a new version of this package, 0.88.0, which will be included in the next Atom release, 0.108.0

**Comment by nkt** [comment]
:+1:

**Pull request merged**
