### PR TITLE
fix: add numeric separators

### LINKED ISSUE #669: Numeric Separators
## Summary

Add support for [numeric separators](https://github.com/tc39/proposal-numeric-separator)

## Motivation

This might be early since they are only at stage 3 as of opening this PR but numeric separators are already in [node LTS](https://node.green/#ESNEXT-candidate--stage-3---numeric-separators) and [Chrome 75](https://www.chromestatus.com/feature/5829906369871872)

## Additional context

https://github.com/tc39/proposal-numeric-separator

### PR DESCRIPTION
**Pull request by UziTech**
## Description of the Change

tokenize numeric separators

### Benefits

numeric separators will be tokenized

### Possible Drawbacks
none

### Applicable Issues
fixes #669

### CODE REVIEW

**Comment by UziTech** [comment]
I'm not sure how to allow multiple separators.

**Comment by UziTech** [comment]
@darangi @sadick254 can this get reviewed?

**Review by sadick254 — APPROVED** [review]
Looks great 👍

**Comment by UziTech** [comment]
Woot 🎉 merged in under a year. I'll take that as a win. lol

**Pull request merged**
