### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by torn4dom4n**

### CODE REVIEW

**Comment by 50Wliu** [comment]
In the future please append `[ci skip]` to commit messages that change only documentation so as to not overload CI.

**Comment by 50Wliu** [comment]
Wow I can't click today.

**Comment by torn4dom4n** [comment]
So tired! :smile:

**Comment by Alhadis** [comment]
[He learns from the best.](https://github.com/atom/language-c/pull/164#pullrequestreview-1424742)

**Pull request merged**
