### PR TITLE
Add JSDoc support for optional parameter types

### PR DESCRIPTION
**Pull request by bgriffith**
This PR adds support for JSDoc highlighting of optional parameter types, defined by suffixing the type with `=` (http://usejsdoc.org/tags-type.html)

`@param {type=} variable - description`

After:

screen shot 2016-08-10 at 20 06 44

### CODE REVIEW

**Comment by 50Wliu** [comment]
The `=` does not need to be escaped.

**Comment by bgriffith** [comment]
@50Wliu Updated!

**Comment by 50Wliu** [comment]
Upon looking at it again, `=?` should suffice, right?  No need for a non-capturing group?

**Comment by bgriffith** [comment]
Heh indeed! Trimmed it down.

**Comment by 50Wliu** [comment]
:+1:

**Pull request merged**
