### PR TITLE
ES6 support

### PR DESCRIPTION
**Pull request by AMalininHere**

### CODE REVIEW

**Comment by lee-dohm** [comment]
I know that the core team is going to ask for specs on this before it gets merged. Would you mind?

**Comment by AMalininHere** [comment]
@lee-dohm I added ES6 classes with specs

**Comment by AMalininHere** [comment]
Added ES6 import support with `as` and `from`

**Comment by kevinsawicki** [comment]
Awesome, thanks for this.

**Comment by lee-dohm** [comment]
:+1:

**Pull request merged**
