### PR TITLE
Don't treat function calls as constant

### PR DESCRIPTION
**Pull request by kartikanand**
Fixes issue #363

### CODE REVIEW

**Comment by 50Wliu** [comment]
Specs please :)

**Comment by kartikanand** [comment]
@50Wliu Yes I was coming to that :) To be honest I currently have no clue as to how to test the spec file locally.

Initially I thought, I should just compile with Coffee and run with Mocha. But compiling is giving the following error:

`ReferenceError: describe is not defined`

Some help? :)

**Comment by 50Wliu** [comment]
`atom --test spec`

**Comment by kartikanand** [comment]
Well the issue is already fixed by @MaximSokolov changes #327  :smile:  (Didn't update my local copy while preparing the pull request :see_no_evil: )

**Comment by MaximSokolov** [comment]
Could you add test for `ABC()` to `describe "function calls", ->` section then please?

**Comment by kartikanand** [comment]
@MaximSokolov  Sure, would do that!

**Pull request merged**
