### PR TITLE
add arrow function snippet

### PR DESCRIPTION
**Pull request by eljefedelrodeodeljefe**
I couldn't find an issue where this simple addition was discussed, so I figured having this PR is alright.

### CODE REVIEW

**Comment by JonathanWolfe** [comment]
A better effort here would be to take all the function snippets and create arrow function alternatives as mentioned in #375.

**Comment by eljefedelrodeodeljefe** [comment]
Can anyone give some guidance on this? Don't know who the maintainers are, maybe @50Wliu

**Comment by 50Wliu** [comment]
I'm fine with merging this for now and creating alternatives in a separate PR.

**Comment by eljefedelrodeodeljefe** [comment]
Thanks.

**Pull request merged**
