### PR TITLE
Relax support.function.js and support.constant.js regex

### PR DESCRIPTION
**Pull request by 50Wliu**
The patterns they match are no longer a hardcoded set of words and are now just `\w+` to match any word sequence.

A side effect of this change is that there can no longer be `support.{function|constant}.dom.js` capturing groups anymore unless you wanted `.dom` to have a specific set of patterns while `support.{function|constant}` didn't.  In that sense, this is a pretty major change.

Refs #137.

### CODE REVIEW

**Comment by impinball** [comment]
I like how that would look.

**Comment by Victorystick** [comment]
Looks great.

**Comment by 50Wliu** [comment]
:ship:

**Comment by kevinsawicki** [comment]
I published 0.88 that included this and bumped it on atom/atom and it caused a few CI failures because of some scope comparisons in some core specs that need to be tweaked:

```
>> TokenizedBuffer
>>   when the buffer contains soft-tabs
>>     when the buffer is fully tokenized
>>       when there is a buffer change that is smaller than the chunk size
>>         when lines are both updated and removed
>>           it updates tokens to reflect the change
>>             Expected { value : 'foo', scopes : [ 'source.js', 'support.function.js' ], isAtomic : false, isHardTab : false, bufferDelta : 3, hasInvisibleCharacters : undefined, hasPairedCharacter : false, isSoftWrapIndentation : false, firstNonWhitespaceIndex : null, firstTrailingWhitespaceIndex : null, screenDelta : 3 } to equal { value : 'foo', scopes : [ 'source.js' ] }.
>>               at [object Object].<anonymous> (/private/var/lib/jenkins/workspace/atom/spec/tokenized-buffer-spec.coffee:200:70)
>>               at _fulfilled (/private/var/lib/jenkins/workspace/atom/node_modules/q/q.js:794:54)
>>               at self.promiseDispatch.done (/private/var/lib/jenkins/workspace/atom/node_modules/q/q.js:823:30)
>>               at Promise.promise.promiseDispatch (/private/var/lib/jenkins/workspace/atom/node_modules/q/q.js:756:13)
>>               at /private/var/lib/jenkins/workspace/atom/node_modules/q/q.js:564:44
>>               at flush (/private/var/lib/jenkins/workspace/atom/node_modules/q/q.js:110:17)
>>               at process._tickCallback (node.js:357:13)
>>         when lines are both updated and inserted
>>           it updates tokens to reflect the change
>>             Expected { value : 'foo', scopes : [ 'source.js', 'support.function.js' ], isAtomic : false, isHardTab : false, bufferDelta : 3, hasInvisibleCharacters : undefined, hasPairedCharacter : false, isSoftWrapIndentation : false, firstNonWhitespaceIndex : null, firstTrailingWhitespaceIndex : null, screenDelta : 3 } to equal { value : 'foo', scopes : [ 'source.js' ] }.
>>               at [object Object].<anonymous> (/private/var/lib/jenkins/workspace/atom/spec/tokenized-buffer-spec.coffee:244:70)
>>               at _fulfilled (/private/var/lib/jenkins/workspace/atom/node_modules/q/q.js:794:54)
>>               at self.promiseDispatch.done (/private/var/lib/jenkins/workspace/atom/node_modules/q/q.js:823:30)
>>               at Promise.promise.promiseDispatch (/private/var/lib/jenkins/workspace/atom/node_modules/q/q.js:756:13)
>>               at /private/var/lib/jenkins/workspace/atom/node_modules/q/q.js:564:44
>>               at flush (/private/var/lib/jenkins/workspace/atom/node_modules/q/q.js:110:17)
>>               at process._tickCallback (node.js:357:13)
>>             Expected { value : 'bar', scopes : [ 'source.js', 'support.function.js' ], isAtomic : false, isHardTab : false, bufferDelta : 3, hasInvisibleCharacters : undefined, hasPairedCharacter : false, isSoftWrapIndentation : false, firstNonWhitespaceIndex : null, firstTrailingWhitespaceIndex : null, screenDelta : 3 } to equal { value : 'bar', scopes : [ 'source.js' ] }.
>>               at [object Object].<anonymous> (/private/var/lib/jenkins/workspace/atom/spec/tokenized-buffer-spec.coffee:245:70)
>>               at _fulfilled (/private/var/lib/jenkins/workspace/atom/node_modules/q/q.js:794:54)
>>               at self.promiseDispatch.done (/private/var/lib/jenkins/workspace/atom/node_modules/q/q.js:823:30)
>>               at Promise.promise.promiseDispatch (/private/var/lib/jenkins/workspace/atom/node_modules/q/q.js:756:13)
>>               at /private/var/lib/jenkins/workspace/atom/node_modules/q/q.js:564:44
>>               at flush (/private/var/lib/jenkins/workspace/atom/node_modules/q/q.js:110:17)
>>               at process._tickCallback (node.js:357:13)
>>             Expected { value : 'baz', scopes : [ 'source.js', 'support.function.js' ], isAtomic : false, isHardTab : false, bufferDelta : 3, hasInvisibleCharacters : undefined, hasPairedCharacter : false, isSoftWrapIndentation : false, firstNonWhitespaceIndex : null, firstTrailingWhitespaceIndex : null, screenDelta : 3 } to equal { value : 'baz', scopes : [ 'source.js' ] }.
>>               at [object Object].<anonymous> (/private/var/lib/jenkins/workspace/atom/spec/tokenized-buffer-spec.coffee:246:70)
>>               at _fulfilled (/private/var/lib/jenkins/workspace/atom/node_modules/q/q.js:794:54)
>>               at self.promiseDispatch.done (/private/var/lib/jenkins/workspace/atom/node_modules/q/q.js:823:30)
>>               at Promise.promise.promiseDispatch (/private/var/lib/jenkins/workspace/atom/node_modules/q/q.js:756:13)
>>               at /private/var/lib/jenkins/workspace/atom/node_modules/q/q.js:564:44
>>               at flush (/private/var/lib/jenkins/workspace/atom/node_modules/q/q.js:110:17)
>>               at process._tickCallback (node.js:357:13)
>>             Expected { value : 'quux', scopes : [ 'source.js', 'support.function.js' ], isAtomic : false, isHardTab : false, bufferDelta : 4, hasInvisibleCharacters : undefined, hasPairedCharacter : false, isSoftWrapIndentation : false, firstNonWhitespaceIndex : null, firstTrailingWhitespaceIndex : null, screenDelta : 4 } to equal { value : 'quux', scopes : [ 'source.js' ] }.
>>               at [object Object].<anonymous> (/private/var/lib/jenkins/workspace/atom/spec/tokenized-buffer-spec.coffee:249:70)
>>               at _fulfilled (/private/var/lib/jenkins/workspace/atom/node_modules/q/q.js:794:54)
>>               at self.promiseDispatch.done (/private/var/lib/jenkins/workspace/atom/node_modules/q/q.js:823:30)
>>               at Promise.promise.promiseDispatch (/private/var/lib/jenkins/workspace/atom/node_modules/q/q.js:756:13)
>>               at /private/var/lib/jenkins/workspace/atom/node_modules/q/q.js:564:44
>>               at flush (/private/var/lib/jenkins/workspace/atom/node_modules/q/q.js:110:17)
>>               at process._tickCallback (node.js:357:13)
```

**Comment by kevinsawicki** [comment]
@50Wliu I'm going to revert this PR to publish around this change and land the other unreleased changes on atom/atom until we figure out the broken specs from this PR.

**Comment by 50Wliu** [comment]
@kevinsawicki I was actually thinking of reverting this myself in order to try to merge this one with #146 :smile:.  When I get back to it I'll make sure to also test the core specs.

**Pull request merged**
