### PR TITLE
use github actions

### PR DESCRIPTION
**Pull request by UziTech**
### Description of the Change

Use github actions for testing instead of travis and appveyor

### Benefits

It works

### Possible Drawbacks

none

### CODE REVIEW

**Comment by UziTech** [comment]
You will have to remove appveyor to prevent it from failing with no `appveyor.yml` file

**Comment by icecream17** [comment]
Aminya submitted a pull request to use github actions too:

https://github.com/atom/language-javascript/pull/684

**Comment by UziTech** [comment]
@aminya Great minds think alike 😁

**Comment by aminya** [comment]
@UziTech Lol 😄

**Pull request closed without merging**
