### PR TITLE
Added delete token

### PR DESCRIPTION
**Pull request by C-Bouthoorn**
Added delete token as noted [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete)

### CODE REVIEW

**Comment by 50Wliu** [comment]
Are you sure this should be under `meta.export.js`?

**Comment by MaximSokolov** [comment]
This rule is supposed to match `var`, `let`... in named exports:
```js
export var x = 0;
export const CONSTANT = 0;
export let scopedVariable = 0;
export function func(p1, p2){}
export class Foo {}
```
btw, I moved these lines up in #276

**Comment by 50Wliu** [comment]
Ok, thanks.  I didn't notice that this rule as a whole was for exports.

**Comment by MaximSokolov** [comment]
Sorry, I wasn't clear. `export delete` is not legit

**Pull request merged**
