### PR TITLE
update tree-sitter packages to 0.16.0

### PR DESCRIPTION
**Pull request by aminya**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

This updates the tree-sitter packages to 0.16.0

### Benefits

Improvements:
 https://github.com/tree-sitter/tree-sitter-javascript/compare/v0.15.2...v0.16.0
 https://github.com/tree-sitter/tree-sitter-jsdoc/compare/v0.15.2...v0.16.0
 https://github.com/tree-sitter/tree-sitter-regex/compare/v0.15.1...v0.16.0

### CODE REVIEW

**Comment by aminya** [comment]
@sadick254 @darangi Please, have a look at this.

**Comment by darangi** [comment]
Hey @aminya is there a reason why you changed [the distro](https://github.com/atom/language-javascript/pull/682/commits/4e6a7bd0b246efeaf1eed82f5bda9644e638ee99)?

**Comment by aminya** [comment]
Travis trusty does not work properly anymore. See the CI run of previous commit.

We should update the distro on all Travis files.

**Comment by darangi** [comment]
Hey @aminya could you fix this conflict? so we merge this?

**Comment by aminya** [comment]
> Hey @aminya could you fix this conflict? so we merge this?

@darangi Done!

**Comment by darangi** [comment]
Thanks @aminya

**Pull request merged**
