### PR TITLE
Update language-javascript.cson

### PR DESCRIPTION
**Pull request by JoeChuCodes**
Added an Alert Snippet i made to help out.

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

I decided to write my own snippets so i looked up how to do this in atom. I noticed that there wasn't one for Alert like there was for Console Log so I decided to write one.
### Alternate Designs

There were none. 
### Benefits

It adds a quick alert syntax so that you can create alerts for any JS file.

### Possible Drawbacks

None that I've seen so far.
### Applicable Issues
None that I've seen thus far.

### CODE REVIEW

**Review by aminya — CHANGES_REQUESTED** [review]
In my opinion, snippets that just simply write a function call should not be included in the default snippets. Because then we should have one snippet for every single function.

This type of autocompletion is already covered by [atom-ide-javascript](https://github.com/atom-community/atom-ide-javascript)

**Comment by JoeChuCodes** [comment]
I was just trying to help

**Comment by aminya** [comment]
> I was just trying to help

I appreciate your help. I was just saying that atom-ide-javascript already includes the autocompletion for the functions. The snippets are usually used to write codes that are related to control flow or the things that write multiple tokens. The function calls would be best kept in the LSP packages. This is especially important if you consider that `alert` is only available in the browser.

**Comment by JoeChuCodes** [comment]
Sorry :(

**Comment by darangi** [comment]
Hi @JoeChuCodes, Thanks for this contribution.

However, we cannot accept this at the moment because there is a way to add custom snippets to atom without updating the grammar packages. Take a look at this [guide](https://flight-manual.atom.io/using-atom/sections/snippets/#creating-your-own-snippets) and explore!

**Pull request closed without merging**
